# Generated by Django 2.2 on 2019-05-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
