# Generated by Django 2.2 on 2019-05-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_delete_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.EmailField(default='1541609448@qq.com', max_length=100),
        ),
    ]
